project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises 1
        menu: 
          - text: Hands-on Exercise 1.1
            href: Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Hands-on Exercise 1.2
            href: Hands-on_Ex1/Hands-on_Ex1_2.qmd
          
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

