project:
  type: website

website:
  title: "Geospatial Data Analytics"
  image: "images/globe.png"
  navbar:
    logo: "images/pusheen-fly.gif"
    title: false
    collapse-below: lg
    search: true
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1.1
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 1.2
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1_2.html
          - text: Hands-on Exercise 2.1
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2_1.html
          - text: Hands-on Exercise 2.2-2.3
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2_2.html
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.html
          - text: Hands-on Exercise 4
            href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4.html
          - text: Hands-on Exercise 5
            href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5.html            
            
      - text: In-class Exercises
        menu: 
          - text: In-Class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-Class Exercise 2
            href: In-class_Ex/In-class_Ex2/In-class_Ex2.html
          - text: In-Class Exercise 3
            href: In-class_Ex/In-class_Ex3/In-class_Ex3.html
          - text: In-Class Exercise 4
            href: In-class_Ex/In-class_Ex4/In-class_Ex4.html
          - text: In-Class Exercise 5
            href: In-class_Ex/In-class_Ex5/In-class_Ex5.html            
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: Take-Home_Ex/Take-Home_Ex1/the1.html    
          - text: Take-home Exercise 2
            href: Take-Home_Ex/Take-Home_Ex2/the2.html              
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  
  page-footer: 
    right: "Blog made with 💜 and [Quarto](https://quarto.org/)"

      

format:
  html:
    grid:
      margin-width: 250px
    toc: true
    toc_float: true
    theme: 
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap
    css: styles.css

editor: visual
