project:
  type: website

website:
  title: "ISSS624"
  navbar:
    background: dark
    search: true
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1.1
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 1.2
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1_2.html
            
      - text: In-class Exercises
        menu: 
          - text: In-Class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html          
    right:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme: sandstone
    mainfont: arial
    fontcolor: "#444444"
    linkcolor: "#716D64"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

